from __future__ import annotations

FONT_BODY = ("Consolas", 10)
FONT_BODY_FAMILY = FONT_BODY[0]
FONT_HEADING_FAMILY = "Bahnschrift SemiBold"
FONT_SECTION = ("Segoe UI", 12, "bold")
FONT_SUBSECTION = ("Segoe UI", 11, "bold")
FONT_PANEL_TITLE = ("Segoe UI", 9, "bold")
FONT_CODE_BOLD = ("Consolas", 10, "bold")
FONT_HEADER_TITLE = ("Bahnschrift SemiBold", 14)
FONT_HEADER_SUBTITLE = ("Consolas", 8)
FONT_STATUS = ("Consolas", 9, "bold")
FONT_MARK_FALLBACK = ("Consolas", 12, "bold")

PAD_PAGE_X = 12
PAD_PAGE_TOP = 12
PAD_ROW = 8
PAD_TIGHT = 6

PANEL_OUTER_PAD_X = 10
PANEL_INNER_PAD_X = 12
PANEL_INNER_PAD_Y = 10
PANEL_GAP = 10
CONTROL_GAP = 8
TEXT_INSET_X = 10
TEXT_INSET_Y = 7
STATUS_INSET_Y = 3

DIALOG_CONTENT_PAD_X = PANEL_INNER_PAD_X
DIALOG_FORM_PAD_X = 16
DIALOG_FORM_PAD_Y = 14
DIALOG_SECTION_WRAP = 700
DIALOG_WIDE_WRAP = 900
DIALOG_FORM_WRAP = 500
